[package]
name = "fractals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
num = "0.4.0"
env_logger = "0.10.0"
pixels = "0.11.0"
winit = "0.28.2"
winit_input_helper = "0.14.0"